name: Sencha Cmd
description: A GitHub Action for Sencha Cmd

inputs:
  dir:
    description: Working directory
    required: true
    default: ./public
  cmd:
    description: Command(s) to run, supports multi lines
    required: true
    default: app build

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.cmd }}
